### ISSUE TITLE
The animation does not work with mootools 1.5.x

### ISSUE THREAD

**Issue by BugBuster1701** [mrpapercut/radialProgressBar#4]
The radial progress bars are only functionally with the option "animate:false". With "true", the bar is always on 100%.
Tested with Mootools 1.5.1

``` html
<script src="http://ajax.googleapis.com/ajax/libs/mootools/1.5.1/mootools-yui-compressed.js"></script>
```

**Comment by mrpapercut** [comment]
Thank you for reporting this!

**Comment by BugBuster1701** [comment]
:+1:  Thanks, it works.
